# Generated by Django 5.2.2 on 2025-06-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='cooking_utensils',
            field=models.TextField(blank=True, help_text='E.g. A stand mixer, A large mixing bowl'),
        ),
        migrations.AddField(
            model_name='post',
            name='steps',
            field=models.TextField(blank=True, help_text='E.g. Step 1. Add 100g of flour to a large mixing bowl'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, help_text='E.g. 100g - flour'),
        ),
    ]
