# Generated by Django 5.2.2 on 2025-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_post_cooking_utensils_post_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
