# Generated by Django 5.2.2 on 2025-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_slug'),
    ]

    operations = [
      migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, help_text="E.g. 100g - flour"),
        )
    ]
