# Generated by Django 5.2.2 on 2025-06-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
