# Generated by Django 5.2.2 on 2025-06-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
