# Generated by Django 5.2.2 on 2025-06-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_updated_on_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
