# Generated by Django 5.2.2 on 2025-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='this-is-the-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
